### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/hr#1141]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] he_employee_lastnames - By @luistorresm - #1156
- [x] hr_contract_employee_calendar_planning - By @jonasbuchholz - #1324
- [x] hr_contract_multi_job - By @AlexPForgeFlow - #1285
- [x] hr_contract_reference - By @jaenbox - #1216
- [ ] hr_contract_type - By @mtelahun - #1321
- [ ] hr_course - By @FernandoRomera - #1172
- [x] hr_course_survey - By @luisDIXMIT - #1383
- [x] hr_department_code - By @ps-tubtim - #1326
- [ ] hr_emergency_contact
- [ ] hr_employee_age - By @destroT - #1220
- [x] hr_employee_birth_name - By @BT-anieto - #1179
- [x] hr_employee_calendar_planning - By @jonasbuchholz - #1290
- [ ] hr_employee_digitized_signature - By @jaenbox - #1187
- [x] hr_employee_document - By @BT-anieto - #1181
- [x] hr_employee_firstname - By @luistorresm - #1154
- [x] hr_employee_id - By @maisim - #1373
- [x] hr_employee_language - By @mymage - #1476
- [x] hr_employee_lastnames - By @luistorresm - #1156
- [ ] hr_employee_medical_examination - By @FernandoRomera - #1174
- [x] hr_employee_partner_external - By @mymage - #1155
- [ ] hr_employee_phone_extension - By @destroT - #1222
- [x] hr_employee_ppe - By @anusriNPS - #1402
- [ ] hr_employee_relative - By @BT-anieto - #1180
- [x] hr_employee_service - By @remi-filament - #1330
- [x] hr_employee_service_contract - By @SoporteOperu - #1226
- [x] hr_employee_ssn - By @FernandoRomera - #1173
- [ ] hr_holidays_settings - By @jterolc - #1244
- [ ] hr_job_category
- [ ] hr_personal_equipment_request
- [x] hr_personal_equipment_stock - By @anusriNPS - #1394

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by luistorresm** [comment]
[hr_employee_firstname](https://github.com/OCA/hr/pull/1154)

**Comment by mymage** [comment]
I migrate:
- hr_employee_partner_external #1155

**Comment by luistorresm** [comment]
[hr_employee_lastnames](https://github.com/OCA/hr/pull/1156)

**Comment by BT-anieto** [comment]
I'm missing modules:
* hr_employee_id
* hr_employee_relative
* hr_employee_ssn
* hr_employee_document

**Comment by BT-anieto** [comment]
[hr_employee_birth_name](https://github.com/OCA/hr/pull/1179)

**Comment by BT-anieto** [comment]
[hr_employee_relative](https://github.com/OCA/hr/pull/1180)

**Comment by BT-anieto** [comment]
[hr_employee_document](https://github.com/OCA/hr/pull/1181)

**Comment by jaenbox** [comment]
[[16.0][MIG] hr_contract_reference: Migration to 16.0](https://github.com/OCA/hr/pull/1216)

**Comment by destroT** [comment]
hr_employee_age -> #1220

**Comment by destroT** [comment]
hr_employee_phone_extension #1222

**Comment by jaenbox** [comment]
[ [16.0][MIG] hr_emergency_contact: Migration to 16.0 #1223 ](https://github.com/OCA/hr/pull/1223)

**Comment by mmarchpunt** [comment]
Migrating /hr_employee_service

**Comment by jterolc** [comment]
[Migration to 16.0 hr_employee_calendar_planning
](https://github.com/OCA/hr/pull/1242)

**Comment by jterolc** [comment]
Migrating hr_holidays_settings

**Comment by jterolc** [comment]
[hr_holidays_settings](https://github.com/OCA/hr/pull/1244) Migrated

**Comment by mmarchpunt** [comment]
Migrating hr_employee_service_contract

**Comment by chusamo** [comment]
hr_employee_phone_extension already migrated #1222

**Comment by chusamo** [comment]
hr_job_category did in #1241

**Comment by chusamo** [comment]
hr_personal_equipment_request did in #1175

**Comment by mmarchpunt** [comment]
hr_employee_service_contract migrated #1245

**Comment by mmarchpunt** [comment]
hr_employee_service migrated #1243

**Comment by mmarchpunt** [comment]
hr_branch #1246

**Comment by alangalva** [comment]
Alguma previsão para a migração do módulo: https://github.com/OCA/hr-expense/tree/15.0/hr_expense_advance_clearing


para versão 16 ?

**Comment by maisim** [comment]
Another PR for hr_employee_id : https://github.com/OCA/hr/pull/1373

**Comment by mymage** [comment]
hr_employee_language migrated (from 13,0) #1476
