### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/hr#157]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] hr_accrual
- [ ] hr_contract_hourly_rate
- [ ] hr_contract_init
- [ ] hr_contract_multi_jobs
- [ ] hr_contract_reference - By @mikevhe18 - #303 
- [ ] hr_contract_state
- [ ] hr_department_sequence - Not needed now (https://github.com/odoo/odoo/blob/9.0/addons/hr/hr.py#L271)
- [ ] hr_emergency_contact - @mikevhe18 - #296 
- [ ] hr_employee_benefit
- [ ] hr_employee_data_from_work_address
- [ ] hr_employee_education
- [x] hr_employee_firstname - By @zakiuu - #254 
- [ ] hr_employee_gravatar
- [ ] hr_employee_id
- [ ] hr_employee_legacy_id - Suggested by @feketemihai to merge in a module hr_employee_id
- [ ] hr_employee_phone_extension
- [ ] hr_employee_reference - By @mikevhe18  - #301 
- [ ] hr_employee_seniority
- [ ] hr_employee_state
- [ ] hr_expense_account_period - To be removed as now there are no periods.
- [ ] hr_expense_analytic_default
- [x] hr_expense_analytic_plans > hr_expense_analytic_distribution - By @cubells - #337 
- [ ] hr_expense_invoice
- [ ] hr_expense_sequence
- [ ] hr_experience
- [ ] hr_experience_analytic
- [ ] hr_family - By @damdam-s - #268 
- [ ] hr_holidays_compute_days - ~~By @rami-wafaie - #264~~ - By @damdam-s - #270
- [ ] hr_holidays_legal_leave #267 @gurneyalex
- [ ] hr_holidays_extension
- [ ] hr_infraction
- [ ] hr_job_categories
- [ ] hr_job_hierarchy
- [ ] hr_labour_recruitment
- [ ] hr_labour_union
- [ ] hr_language
- [ ] hr_payroll_extension
- [ ] hr_payroll_period
- [ ] hr_payroll_register
- [ ] hr_payroll_register_report
- [ ] hr_payslip_amendment
- [ ] hr_payslip_ytd_amount
- [ ] hr_policy_absence
- [ ] hr_policy_accrual
- [ ] hr_policy_group
- [ ] hr_policy_ot
- [ ] hr_policy_presence
- [x] hr_public_holidays - By @rami-wafaie - #263
- [ ] hr_report_manpower
- [ ] hr_report_payroll_attendance_summary
- [ ] hr_report_payroll_net
- [ ] hr_report_turnover
- [ ] hr_resume
- [ ] hr_salary_rule_reference
- [ ] hr_salary_rule_variable
- [ ] hr_schedule
- [ ] hr_security - It seems to work directly from 8.0 (source: #326)
- [ ] hr_simplify
- [ ] hr_skill - By @nicomacr - #299 
- [ ] hr_transfer
- [ ] hr_wage_increment
- [ ] hr_webcam
- [ ] hr_worked_days_activity
- [ ] hr_worked_days_from_timesheet - By @lreficent - #329 
- [ ] hr_worked_days_hourly_rate - By @kossovo - #170

**Comment by ghost** [comment]
@sbidoul @pedrobaeza Could I ask why you put modules out of **unported** for v9 ? This seems a very odd decision. Could you point me the discussion on this matter ?

**Comment by yvaucher** [comment]
@dufresnedavid This was discussed in mailing list and agreed. `__unported__` directory is a nighmare in term of git history. Thus we only set installable to False.

**Comment by ghost** [comment]
@yvaucher I agree **unported** is a mess, but the real nightmare is having a directory full of unported modules. I was not in your mailing list loop so I missed the debate. I think the community is making a huge mistake. The option to use filter-branch is cleaner. But what is done is done.

**Comment by pedrobaeza** [comment]
Well, David, that was a long debate, and my first option indeed was not to leave unported on root, but some arguments like git-filter-branch miss part of the history when a module is renamed, make to select this option.

For your reference, this is the mail thread (started on august): https://odoo-community.org/groups/contributors-15/oca-contributors-24594?mode=thread&date_begin=&date_end=

And you should subscribe to contributors list, because is the main axis for OCA contributions.

**Comment by gurneyalex** [comment]
I'm starting to work on some v9 migrations (yeah I know it's a bit late, but the customer has the final word on this)...

**Comment by pedrobaeza** [comment]
Please assign yourself in the issue to avoid effort duplications

**Comment by damdam-s** [comment]
@pedrobaeza  `hr_holidays_compute_days`  is now on #270
