### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/hr#259]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] hr_contract_default_trial_length
- [ ] hr_contract_hourly_rate
- [ ] hr_contract_init
- [ ] hr_contract_multi_jobs
- [x] hr_contract_reference - By @leemannd - #316 
- [ ] hr_contract_state
- [ ] hr_department_sequence
- [x] hr_emergency_contact - By @leemannd - #314 
- [x] hr_employee_age - By @Yopli2k - #293 
- [ ] hr_employee_benefit
- [ ] hr_employee_birth_date - Even that the module is already ported, the field is already present in Odoo as a date (https://github.com/odoo/odoo/blob/10.0/addons/hr/models/hr.py#L113)
- [ ] hr_employee_data_from_work_address
- [x] hr_employee_firstname - @espo-tony - #276  
- [ ] hr_employee_gravatar
- [x] hr_employee_id - By @astirpe - #272 
- [ ] hr_employee_legacy_id
- [x] hr_employee_phone_extension - By @leemannd - #313 
- [ ] hr_employee_reference
- [ ] hr_employee_seniority
- [ ] hr_expense_account_period - See #399 
- [ ] hr_expense_analytic_default
- [x] hr_expense_analytic_plans > hr_expense_analytic_distribution - By @cubells - #388 
- [x] hr_expense_invoice - By @cubells - #367 
- [ ] hr_expense_move_date - DEPRECATED - see #393
- [ ] hr_expense_sequence
- [x] hr_experience - By @jlaloux - #306 
- [ ] hr_family
- [x] hr_holidays_leave_auto_approve - By @espo-tony - #271 
- [x] hr_holidays_compute_days - By @yelizariev - #261 
- [x] hr_holidays_legal_leave - By @yelizariev - #262 
- [ ] hr_infraction
- [ ] hr_job_categories
- [ ] hr_job_hierarchy
- [ ] hr_labour_union
- [ ] hr_language - By @acsonefho - #380 
- [ ] hr_payroll_register
- [ ] hr_payslip_amendment
- [ ] hr_payslip_move_date
- [ ] hr_payslip_ytd_amount - By @bassn - #278 
- [ ] hr_policy_absence
- [ ] hr_policy_accrual
- [ ] hr_policy_group
- [ ] hr_policy_ot
- [ ] hr_policy_presence
- [x] hr_public_holidays - By @yelizariev - #261 
- [ ] hr_recruitment_partner
- [ ] hr_resume
- [ ] hr_salary_rule_reference
- [ ] hr_salary_rule_variable
- [ ] hr_schedule
- [ ] hr_security
- [x] hr_skill - ~~By @jlaloux - #300~~ By @leemannd - #378
- [ ] hr_transfer
- [ ] hr_wage_increment
- [ ] hr_webcam
- [ ] hr_worked_days_activity
- [ ] hr_worked_days_from_timesheet
- [ ] hr_worked_days_hourly_rate
# TODO
- Several HR base resources renamed:
  
  ``` bash
  find . -type f -name '*.xml' | xargs sed -i 's/menu_hr_configuration/menu_human_resources_configuration/g'
  find . -type f -name '*.csv'  -o -name '*.py' -o -name '*.xml'  | xargs sed -i 's/base.group_hr/hr.group_hr/g'
  ```

**Comment by yelizariev** [comment]
@pedrobaeza you can add #261 to hr_public_holidays too

**Comment by pedrobaeza** [comment]
Please only 1 module per PR.

**Comment by yelizariev** [comment]
`hr_holidays_compute_days` depends on `hr_public_holidays`. It means that people has to wait for merging `hr_public_holidays` before being able to review `hr_holidays_compute_days`. Also, `hr_public_holidays` has very few changes

**Comment by pedrobaeza** [comment]
No, no need to wait. You make 2 PRs: one with `hr_public_holidays`, and another containing the previous commits + the module `hr_holidays_compute_days`, and mark as dependent. When the first one is merged, you only need to rebase. This is for making easier to merge PRs. If you include 2 modules, it will be more difficult to review, and less chances to be merged.

**Comment by yelizariev** [comment]
I mean, that runbot and travis will not work, if hr_public_holidays is not installable.

**Comment by pedrobaeza** [comment]
It will work. Second PR must include all the commits from the first one (the migration of `hr_public_holidays`), plus the commit/s for migrating the module `hr_holidays_compute_days`. This way, you can review the first PR, as well as reviewing code from specific commits in the second PR, or reviewing functionally the second one. If the first one gets merged, you rebase the second one and you have the second PR clean with only the commits for the second module.

Do you understand the process?

**Comment by yelizariev** [comment]
Got it. Thank you for explanantion

Unfortunately, I already have commits, that make updates on both modules. I will separate it later if needed. I will definitely use this approach on next PRs

**Comment by pedrobaeza** [comment]
OK, let's continue this time having both in one PR, but please take note for future times.

**Comment by astirpe** [comment]
Porting hr_employee_id: #272

**Comment by leemannd** [comment]
Porting hr_employee_phone_extension: https://github.com/OCA/hr/pull/313

**Comment by leemannd** [comment]
Porting hr_emergency_contact: https://github.com/OCA/hr/pull/314

**Comment by leemannd** [comment]
Porting hr_contract_reference: https://github.com/OCA/hr/pull/316

**Comment by leemannd** [comment]
And a last one for now. Porting hr_employee_seniority: https://github.com/OCA/hr/pull/319

**Comment by damdam-s** [comment]
#370 migration to v10 of `hr_holidays_validity_date`

**Comment by leemannd** [comment]
@pedrobaeza As we get few (no) answer from the author of https://github.com/OCA/hr/pull/300 and he is having trouble rebasing his work, can we superseed with https://github.com/OCA/hr/pull/378 ?
I have cherry-picked his actual work and I'm going to test it before the end of the week.

**Comment by pedrobaeza** [comment]
@leemannd Done
