### ISSUE TITLE
Payroll modules

### ISSUE THREAD

**Issue by max3903** [OCA/hr#74]
- [x] Payroll analysis : #72
- [x] Add payslip with year-to-date amount and translated lines : #69
- [x] Added leave accruals module : #34
- [x] Worked Days from Timesheet with Activities : #76 
- [x] Add public holidays to the leave types : #78
- [x] Add Employee exemption #83
- [x] Add HR Employee Benefits : #82

**Comment by charbeljc** [comment]
#82 was merged yesterday,  #76 has three approvals, issue could be closed now.
