### ISSUE TITLE
Migration to version 8

### ISSUE THREAD

**Issue by max3903** [OCA/hr#86]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-8
# Modules to migrate
- [x] hr_contract_hourly_rate by @feketemihai  in #92 
- [ ] hr_contract_init
- [x] hr_contract_multi_jobs by @feketemihai in #91
- [x] hr_contract_reference by @feketemihai in #94 
- [ ] hr_contract_state
- [x] hr_department_sequence by @adrienpeiffer in #123 
- [x] hr_emergency_contact by @Zwygart in #125 / #204 
- [x] hr_employee_firstname by @adrienpeiffer  in #127 
- [x] hr_employee_id by @tarzan0820 in #134 / #205 
- [x] hr_employee_legacy_id by @adrienpeiffer in #120 
- [x] hr_employee_phone_extension by @charbeljc in #112 
- [ ] hr_employee_seniority
- [x] hr_expense_sequence by @pedrobaeza in #70 
- [x] hr_experience by @feketemihai  in #100
- [x] hr_family by @sebalix in #90 
- [x] hr_infraction by @andhit-r in #207 
- [x] hr_job_categories by @feketemihai in #95 
- [ ] hr_job_hierarchy
- [ ] hr_labour_union by @ehdem in #144 
- [x] hr_language by @sebalix in #89 
- [ ] hr_policy_absence
- [ ] hr_policy_accrual
- [ ] hr_policy_group
- [ ] hr_policy_ot
- [ ] hr_policy_presence
- [ ] hr_resume by @Ehtaga 
- [ ] hr_schedule
- [x] hr_security by @feketemihai in #96 
- [x] hr_skill by @dreispt in #124 
- [ ] hr_transfer by @tarzan0820 in #216 
- [ ] hr_wage_increment
- [x] hr_webcam by @yoyo2k in #65 
## Modules used for payroll

In order of dependencies
- [ ] hr_period by @tarzan0820 in #145 
- [x] hr_public_holidays by @grzekru in #85 / #209 
- [x] hr_salary_rule_reference by @dufresnedavid in #137
- [ ] hr_employee_exemption by @Zwygart in #121 @dufresnedavid in #165 
- [ ] hr_worked_days_hourly_rate by @coleste in #122 @acysos in #188 
- [x] hr_employee_benefit by @dufresnedavid in #137
- [x] hr_worked_days_from_timesheet by @acysos in #189 
- [ ] hr_employee_benefit_exemption by @vincentcoll 
- [ ] hr_employee_benefit_on_job by @elemire 
- [ ] hr_employee_benefit_percent
- [ ] hr_leave_accruals
- [ ] hr_payroll_analysis by @tarzan0820 in #150 
- [ ] hr_payroll_register
- [ ] hr_payslip_amendment by @tarzan0820 in #141 
- [ ] hr_payslip_ytd_amount
- [ ] hr_salary_rule_variable
- [ ] hr_worked_days_activity_from_timesheet
- [ ] hr_activity_on_timesheet
## Modules to be deprecated starting from 8.0
- [x] hr_accrual in #227
- [x] hr_employee_education in #233 
- [x] hr_employee_state in #234 
- [x] hr_experience_analytic in #228 
- [x] hr_holidays_extension incorporated by @tarzan0820 / @feketemihai in #210 
- [x] hr_labour_recruitment in #229 
- [ ] hr_simplify by @feketemihai  in #97 
- [ ] hr_worked_days_activity by @naousse

**Comment by feketemihai** [comment]
Migration of hr_contract_multi_jobs in #91 and hr_contract_hourly_rate in #92

**Comment by yvaucher** [comment]
@feketemihai Thanks, list updated

**Comment by Zwygart** [comment]
Migrated hr_employee_exemption

**Comment by Zwygart** [comment]
I'll take the hr_emergency_contact also

**Comment by mmalorni** [comment]
marcetiennedery et cybermtl travaillent sur le module hr_salary_rule_reference

**Comment by ehdem** [comment]
@max3903 : I am working on this module hr_labour_union

**Comment by Ehtaga** [comment]
@max3903 I'm on hr_resume

**Comment by vincentcoll** [comment]
@vincentcoll working on hr_employee_benefit_exemption

**Comment by elemire** [comment]
I'm working on hr_employee_benefit_on_job

**Comment by mmalorni** [comment]
Il faudrait updater la liste ci-dessus pour le #137 et le #85 qui sont mergés.

**Comment by max3903** [comment]
#85 is not merged yet.

**Comment by ovnicraft** [comment]
hi i did some changes recenlty to 8.0 at my fork... i will put a PR ASAP

https://github.com/ovnicraft/hr
